import localFont from "next/font/local";
import "@/styles/client/global.css";
import "materialize-css/dist/css/materialize.min.css";
import "bootstrap-icons/font/bootstrap-icons.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import HeadTag from "@/components/head";
import FixElement from "@/components/miniElementHelper/fixElement";
import Navbar from "@/components/navbar";
import "@/styles/client/helper.css";
import ToggleMenuContext from "@/context/showMenuState";
import Footer from "@/components/footer";

const coutomFont = localFont({ src: "../../public/fonts/FiraCode-Regular.ttf" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <HeadTag />
      <body className={coutomFont.className}>
        <ToggleMenuContext>
          <FixElement />
          <Navbar />
          {children}
          <Footer/>
        </ToggleMenuContext>
      </body>
    </html>
  );
}
